# Generated by Django 2.2.12 on 2021-12-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='users',
            name='link_change',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='link_delete',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users_base',
        ),
    ]
