# Generated by Django 2.2.12 on 2021-12-13 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_auto_20211210_0938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
