# Generated by Django 3.1.4 on 2022-01-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0002_auto_20220117_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, through='tasks.Task_Label', to='labels.Labels', verbose_name='Метки'),
        ),
    ]
