language: python
python: 3.8

services:
  - postgresql

before_install:
  - pip install poetry

install:
  - make install

before-script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - make prepare

script:
  - make check

after_script:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

#name: linter_and_test
#
#on:
#  push:
#    branches:
#      - '**'
#    tags:
#      - '**'
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-python@v2
#      - name: updating dpendencies and do linter check
#        run: |
#          pip install poetry
#          make install
#          make lint
#      - name: Test & publish code coverage
#        uses: paambaati/codeclimate-action@v2.7.5
#        env:
#          CC_TEST_REPORTER_ID: ${{ secrets.TOKEN_4_PROJECT }}
#        with:
#          coverageCommand: make test
#      - name: Build
